sudo: required
dist: xenial
services:
  - docker
language: ruby
rvm:
  - "2.2"
  - "2.6"
  - ruby-head
env:
  - "PGVERSION=11"
  - "PGVERSION=9.3"
  - "PGCROSS=true"
matrix:
  # Test cross compilation only with 2.6
  exclude:
    - rvm: "2.2"
      env: "PGCROSS=true"
    - rvm: ruby-head
      env: "PGCROSS=true"
  allow_failures:
    - rvm: ruby-head
  fast_finish: true
before_install:
  - gem install bundler
  - bundle install
  # Download and install postgresql version to test against in /opt (for non-cross compile only)
  - |
    if [ -z "$PGCROSS" ]; then
      echo "deb http://apt.postgresql.org/pub/repos/apt/ xenial-pgdg main $PGVERSION" | sudo tee -a /etc/apt/sources.list.d/pgdg.list && \
      wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add - && \
      sudo apt -y update && \
      sudo apt -y --allow-downgrades install postgresql-$PGVERSION libpq5=$PGVERSION* libpq-dev=$PGVERSION* && \
      export PATH=/usr/lib/postgresql/$PGVERSION/bin:$PATH
    fi
script: |
  if [ -z "$PGCROSS" ]; then
    rake compile test
  else
    # Create a dummy cert to satisfy the build
    ruby -ropenssl -e "puts OpenSSL::PKey::RSA.new(2048).to_pem" > ~/.gem/gem-private_key.pem && \
    gem cert --build travis-ci@dummy.org --private-key ~/.gem/gem-private_key.pem && \
    cp gem-public_cert.pem ~/.gem/gem-public_cert.pem && \
    rake gem:windows
  fi
